version:
  server: "1.0.0"

resource:
  # 상대 경로 사용 (크로스 플랫폼 호환)
  data: "./storage"
  mcp: "./mcp_agent/servers"

path:
  chat: "./chat-data"
  file: "./data-store"
  chroma: "./chroma-db"

log:
  path: "./vibecraft-code-python-log"
