version:
  server: "1.0.0"

resource:
  data: "[YOUR_PATH]/vibecraft-code/storage"
  mcp: "[YOUR_PATH]/vibecraft-code/mcp_agent/servers"

path:
  chat: "./chat-data"
  file: "./data-store"
  chroma: "./chroma-db"

log:
  path: "./vibecraft-code-python-log"
